### ISSUE TITLE
[Documentation] Config file

### ISSUE THREAD

**Issue by mart3323** [Johannes7k75/classCommandSystem#3]
in Client.js, i can see that it will read a 'config' file and make it available to commands - this is not documented nor shown in the example command.

---
Additional nitpick:
The config file is read from one level higher than the root - Perhaps it would make sense for the config file to be on the root level instead so that the whole system is self-contained.

**Comment by Johannes7k75** [comment]
This is for all your issues:
- Yes all things are going to be documented and made relative
 
I just finished it at 1:40 and i just wanted it to be in github.
Im going to do that in the next 1-5 days eastern and so...

**Comment by mart3323** [comment]
yep, no hurry - consider this a todo/reminder then ^^

**Comment by Johannes7k75** [comment]
It it yet clearly what to do with the config?
